name: Run Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: Root
          server: 138.68.64.248
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          local_path: ./* # default is ./*
          remote_path: /home/server_try_out/

          args: '-o ConnectTimeout=5'